services:
  - type: web
    name: cinema
    runtime: php
    region: oregon # Or your preferred region
    plan: free # Change to a paid plan if needed
    buildCommand: |
      # Install PHP dependencies
      composer install --no-dev --optimize-autoloader
      # Run any migrations
      php artisan migrate --force
      # Cache Laravel configurations and routes
      php artisan config:cache
      php artisan route:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: cinema-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cinema-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: cinema-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: cinema-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cinema-db
          property: password

databases:
  - name: cinema-db
    plan: free
    databaseName: cinema_db
    user: cinema_user
